all:
	gcc open.c -o open
	gcc destroy.c -o destroy
	gcc query.c -o query
	gcc take.c -o take
	gcc save.c -o save
	gcc transfer.c -o transfer
	gcc server.c -o s
	gcc client.c
clearn:
	rm open destroy query take save transfer s a.out
